### ISSUE TITLE
Live progress reporting

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#5]
## User Story
As a developer, I would like to see live progress so that I can estimate how much time is left.

## Detailed Description
- [ ] Add functionality to the Client or JobOrderer when a job has been completed.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

## Estimated points
1

**Comment by yashlala** [comment]
Are we still going for this?

**Comment by rvighne** [comment]
> Are we still going for this?

Yes. This is a very simple feature to implement on the controller side. Just `console.log` whenever you get an event saying a job completed.
